### ISSUE TITLE
error in runnig data.sh

### ISSUE THREAD

**Issue by ykkhan** [Tikquuss/meta_XLM#3]
When I run this command it results in this error.
![Screenshot from 2020-08-30 18-09-07](https://user-images.githubusercontent.com/42977303/91660246-afc10500-eaee-11ea-9202-0fe65a3cc8cd.jpg)

**Comment by Tikquuss** [comment]
I just added an [illustrative notebook](https://colab.research.google.com/github/Tikquuss/meta_XLM/blob/master/notebooks/demo/tuto.ipynb) to the repository.
Please take it as an example and read the readme for more details (it has also been modified accordingly).
I modified the data.sh file, I hope your error will be solved.
