### ISSUE TITLE
No known abbreviations for language 'da', attempting fall-back to English version...

### ISSUE THREAD

**Issue by sadanyh** [Tikquuss/meta_XLM#4]
Hi

Thank you very much for the tutorial. I am trying to train an XML with (TM) objective on dialectical Arabic, and modern standard Arabic. I use da and ms as the abbreviations for the languages. When I try to run the data.sh to preprocess the data I get this error:

No known abbreviations for language 'da', attempting fall-back to English version...

Is there any parameter that I need to change? I changed the names of the languages to da and ms in the "apply_bpe_preprocess.sh". But still get the error. Thank you for your help

**Comment by sadanyh** [comment]
I managed to solve this problem by choosing a different abbreviation to my language pairs, ones that are already there.

Thanks

**Comment by Tikquuss** [comment]
This is not an error as such, just an alert. Take a look [here](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/tokenizer/tokenizer.perl#L567-L573).

You don't have a specialized tokenizer for your language in moses, so the English one is used by default.
